export {default as News} from './News';
export {default as Aside} from './Aside/Aside';
export {default as Dialogs} from './Dialogs/Dialogs';
export {default as Header} from './Header/Header';
export {default as Profile} from './Profile/Profile';
export {default as ProfileInfo} from './Profile/ProfileInfo/ProfileInfo';
export {default as Footer} from './Footer/Footer';
export {default as Music} from './Music';
export {default as Settings} from './Settings';